name: DisguiseTester
main: pgDev.bukkit.DisguiseTester.DisguiseTester
version: 0.5
author: PG Dev Team
authors: [Devil Boy]
description: Experiment with disguises!
depend: [DisguiseCraft]
softdepend: [SpoutPlugin]

commands:
   dt:
      description: The main disguise testing command.
      usage: /<command>
   dpacket:
      description: The packet manipulation command.
      aliases: [dp]
      usage: /<command>

permissions:
    disguisetester.disguise.create:
        default: op
        description: Can create test disguises.
    disguisetester.disguise.wear:
        default: op
        description: Can wear test disguises.