name: DisguiseTester
main: pgDev.bukkit.DisguiseTester.DisguiseTester
version: 1.1
author: PG Dev Team
authors: [Devil Boy]
description: Experiment with disguises!
softdepend: [DisguiseCraft, ProtocolLib]

commands:
   dt:
      description: The main disguise testing command
      usage: /<command>
   dtsu:
      description: Runs command as another player
      usage: /<command> <player> <commands>
   dtprofile:
      description: Output player profiles
      usage: /<command> [player]
   dtscan:
      description: Scan packets
      usage: /<command>

permissions:
    disguisetester.disguise.create:
        default: op
        description: Can create test disguises
    disguisetester.disguise.wear:
        default: op
        description: Can wear test disguises
    disguisetester.disguise.scroll:
        default: op
        description: Can scroll through DisguiseCraft disguises
    disguisetester.su:
        default: op
        description: Can run commands as other users
    disguisetester.profile:
        default: op
        description: Can check GameProfile info
    disguisetester.packet.scan:
        default: op
        description: Can scan packets