name: DisguiseTester
main: pgDev.bukkit.DisguiseTester.DisguiseTester
version: 0.7
author: PG Dev Team
authors: [Devil Boy]
description: Experiment with disguises!
depend: [DisguiseCraft]

commands:
   dt:
      description: The main disguise testing command
      usage: /<command>
   dtsu:
      description: Runs command as another player
      usage: /<command> <player> <commands>

permissions:
    disguisetester.disguise.create:
        default: op
        description: Can create test disguises
    disguisetester.disguise.wear:
        default: op
        description: Can wear test disguises
    disguisetester.disguise.scroll:
        default: op
        description: Can scroll through DisguiseCraft disguises
    disguisetester.su:
        default: op
        description: Can run commands as other users